/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-1",
  aws_cognito_identity_pool_id:
    "us-east-1:23b2de95-9c98-414f-8f1c-fe8f4e14078f",
  aws_cognito_region: "us-east-1",
  aws_user_pools_id: "us-east-1_NzXu7kKmV",
  aws_user_pools_web_client_id: "5hrj3kt9qrno8tn16277smkp8",
  oauth: {},
};

export default awsmobile;
//wtf
